/* eslint-disable import/no-unused-modules */
export const APPLICATION_BOOTED = 'APPLICATION_BOOTED';
export const APPLIATION_SAVE_QUOTE = 'APPLIATION_SAVE_QUOTE';
export const LOADING_ADDRESS_DATA = 'LOADING_ADDRESS_DATA';
export const LOAD_TICKET_CHECKER = 'LOAD_TICKET_CHECKER';

export const START_WAITING_ROOM = 'START_WAITING_ROOM';
export const FINISH_WAITING_ROOM = 'FINISH_WAITING_ROOM';

export const RESET_SESSION = 'RESET_SESSION';
export const CHECK_LOAN_TRESHOLD = 'CHECK_LOAN_TRESHOLD';
export const VERIFY_EMAIL = 'VERIFY_EMAIL';

export const APPLICATION_UPDATE_BREADCRUMBS = 'APPLICATION_UPDATE_BREADCRUMBS';

export const REQUEST_PASSWORD_RESET = 'REQUEST_PASSWORD_RESET';
export const REQUEST_VERIFICATION_EMAIL = 'REQUEST_VERIFICATION_EMAIL';
export const LOAD_DEV_SESSION_DETAILS = 'LOAD_DEV_SESSION_DETAILS';
