export REACT_APP_AUTH0_CLIENTID=${REACT_APP_AUTH0_CLIENTID:-}
export REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN:-}
export REACT_APP_AUTH0_CALLBACK_URL=${REACT_APP_AUTH0_CALLBACK_URL:-}
export REACT_APP_AUTH0_ALLOWED_CONNECTIONS=${REACT_APP_AUTH0_ALLOWED_CONNECTIONS:-}
export REACT_APP_SENTRY_DSN=${REACT_APP_SENTRY_DSN:-}
export REACT_APP_WORLDPAY_KEY=${REACT_APP_WORLDPAY_KEY:-}

export REACT_APP_BASE_URL=${REACT_APP_BASE_URL:-}
export REACT_APP_BRAND_NAME=${REACT_APP_BRAND_NAME:-}
export REACT_APP_URL_MAPPER=${REACT_APP_URL_MAPPER:-}
export REACT_APP_START_JOURNEY_ENDPOINT=${REACT_APP_START_JOURNEY_ENDPOINT:-i_want_a_stubbed_loan}
export REACT_APP_FRONTEND_STUBS_BY_DEFAULT=${REACT_APP_FRONTEND_STUBS_BY_DEFAULT:-}
